version: '3.4'

services:
  builder-comfyui:
    profiles: [builder, builder-comfyui]
    build:
      context: ./build
      target: comfyui-comfyui
    image: comfyui-comfyui

  builder-ootd:
    profiles: [builder, builder-ootd]
    build:
      context: ./build
      target: comfyui-ootd
    image: comfyui-ootd

  builder-3dpack:
    profiles: [builder, builder-3dpack]
    build:
      context: ./build
      target: comfyui-3dpack
    image: comfyui-3dpack
    
  comfyui:
    profiles: [comfyui, comfyui-comfyui]
    image: comfyui-comfyui
    ports:
      - "8188:8188"
    environment:      
      HTTP_PROXY: $HTTP_PROXY
      HTTPS_PROXY: $HTTPS_PROXY
      NO_PROXY: $NO_PROXY
      HF_ENDPOINT: $HF_ENDPOINT
    volumes:
      - ./instances/comfyui:/home/ComfyUI/app
      - ./models:/home/ComfyUI/app/models
      - ./input:/home/ComfyUI/app/input
      - ./output:/home/ComfyUI/app/output
      - ./workflows:/home/ComfyUI/app/pysssss-workflows
      - ./docs:/home/ComfyUI/app/web/docs
      - ./cache/huggingface:/home/ComfyUI/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

  comfyui-ootd:
    profiles: [comfyui, comfyui-ootd]
    image: comfyui-ootd
    ports:
      - "8187:8188"
    environment:      
      HTTP_PROXY: $HTTP_PROXY
      HTTPS_PROXY: $HTTPS_PROXY
      NO_PROXY: $NO_PROXY
      HF_ENDPOINT: $HF_ENDPOINT
    volumes:
      - ./instances/ootd:/home/ComfyUI/app
      - ./models:/home/ComfyUI/app/models
      - ./input:/home/ComfyUI/app/input
      - ./output:/home/ComfyUI/app/output
      - ./workflows:/home/ComfyUI/app/pysssss-workflows
      - ./docs:/home/ComfyUI/app/web/docs
      - ./cache/huggingface:/home/ComfyUI/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

  comfyui-3dpack:
    profiles: [comfyui, comfyui-3dpack]
    image: comfyui-3dpack
    ports:
      - "8186:8188"
    environment:
      HTTP_PROXY: $HTTP_PROXY
      HTTPS_PROXY: $HTTPS_PROXY
      NO_PROXY: $NO_PROXY
      HF_ENDPOINT: $HF_ENDPOINT
    volumes:
      - ./instances/3dpack:/home/ComfyUI/app
      - ./models:/home/ComfyUI/app/models
      - ./input:/home/ComfyUI/app/input
      - ./output:/home/ComfyUI/app/output
      - ./workflows:/home/ComfyUI/app/pysssss-workflows
      - ./docs:/home/ComfyUI/app/web/docs
      - ./models/crm:/home/ComfyUI/app/custom_nodes/ComfyUI-3D-Pack/checkpoints/crm
      - ./cache/huggingface:/home/ComfyUI/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
